/***
 * Cobalt (C++ Rewrite) - ASCII Art
 * Copyright (C) 2018-2023  Jonathon Gosselin
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 ***/
void drawCharacterFromSet(Canvas* canvas,int chracterIndex);
void drawTypedCharacter(Canvas* canvas, char typedCharacter);
void resetCharacter(Canvas* canvas);
void showFullDrawing(Canvas* canvas);
void redrawRegion(Canvas* canvas, int startX, int startY, int endX, int endY);
